---
driver:
  name: vagrant

provisioner:
  name: chef_solo

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: centos-7.1
    driver:
      network:
      - ["private_network", {ip: "192.168.0.10"}]
      customize:
        memory: 1536

suites:
  - name: server
    run_list:
      - recipe[chef-server::default]
    attributes:
